services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    restart: unless-stopped
    container_name: sqlserver_cmp
    environment:
      - SA_PASSWORD=PasswordHereLa
      - ACCEPT_EULA=Y
      - MSSQL_USER=userherela
      - MSSQL_PASSWORD=Password2HereLa
      - MSSQL_DATABASE=database
    ports:
      - "1433:1433"

  postgresql:
    image: postgres:latest
    restart: unless-stopped
    container_name: postgresql_cmp
    environment:
      - POSTGRES_USER=user2herela
      - POSTGRES_PASSWORD=Password3HereLa
      - POSTGRES_DB=database2
    ports:
      - "5432:5432"

  pgadmin:
    image: dpage/pgadmin4:latest
    restart: unless-stopped
    container_name: pgadmin_cmp
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=Password4HereLa
      - PGADMIN_LISTEN_PORT=80
      - PGADMIN_CONFIG_SERVER_MODE=False
    ports:
      - "5050:80"
    depends_on:
      - postgresql

  nifi:
    image: apache/nifi:latest
    restart: unless-stopped
    container_name: nifi_cmp
    ports:
      - "8443:8443"
    volumes:
      - drivers_location:/opt/nifi/nifi-current/lib
      