CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;
CREATE TABLE "Books" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Title" text,
    "Author" text,
    "ISBN" text,
    "PublishedDate" timestamp without time zone NOT NULL,
    CONSTRAINT "PK_Books" PRIMARY KEY ("Id")
);

CREATE TABLE "Users" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Login" text,
    "Email" text,
    "FirstName" text,
    "LastName" text,
    "BirthDate" timestamp without time zone NOT NULL,
    "Height" numeric NOT NULL,
    CONSTRAINT "PK_Users" PRIMARY KEY ("Id")
);

CREATE TABLE "Rentals" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "RentalDate" timestamp without time zone NOT NULL,
    "ReturnDate" timestamp without time zone,
    "BookId" integer,
    "UserId" integer,
    CONSTRAINT "PK_Rentals" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Rentals_Books_BookId" FOREIGN KEY ("BookId") REFERENCES "Books" ("Id"),
    CONSTRAINT "FK_Rentals_Users_UserId" FOREIGN KEY ("UserId") REFERENCES "Users" ("Id")
);

CREATE INDEX "IX_Rentals_BookId" ON "Rentals" ("BookId");

CREATE INDEX "IX_Rentals_UserId" ON "Rentals" ("UserId");

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20250403182048_PostgreSqlInit', '9.0.3');

COMMIT;

